title: GeoSim
subtitle: ACM SIGSPATIAL International Workshop on GeoSpatial Simulation
preposition: at
description: >-
  Monday October 29, 2024, Atlanta, Georgia, USA
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://geo-sim.github.io" # the base hostname & protocol for your site, e.g. https://example.com

remote_theme: DigitaleGesellschaft/jekyll-theme-conference@v3.6.1

# Build settings
markdown: kramdown
sass:
  style: compressed

# Additional exclude from processing
exclude:
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:year/:collection/:title/
  speakers:
    output: true
    permalink: /:year/:collection/:title/
  rooms:
    output: true
    permalink: /:year/:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room


conference:

  # Language
  lang: en

  # Show theme errors:
  show_errors: False

  # Navigation bar
  navigation:
    # logo:
    #   name: ACM SIGSPATIAL
    #   img: 'acmsigspatial-full.png'
    #   url: 'https://geosim.org/'
    links:
      - name: Call For Paper
        relative_url: /cfp/
      - name: Organizers
        relative_url: /organizers/
      - name: Program
        relative_url: /program/
      - name: Talks
        relative_url: /talks/
      - name: Speakers
        relative_url: /speakers/
      # - name: Location
      #   relative_url: /location/
      - name: Previous
        menu:
          - name: 2024 (current)
            relative_site_url: /2024/
          - name: 2023
            relative_site_url: /2023/
          - name: 2022
            absolute_url: https://geosim2022.blogspot.com
          - name: 2021
            absolute_url: http://www.2021.geosim.org
          - name: 2020
            absolute_url: http://www.2020.geosim.org
          - name: 2019
            absolute_url: https://www.2019.geosim.org
          - name: 2018
            absolute_url: https://www.2018.geosim.org


  # Link Preview for Sharing
  link_preview:
    # also adapt "preposition" property at top for more meaningful descriptions
    disable: false
    img:
      twitter: 'twitter_preview.png'      # inside /assets/images/
      open_graph: 'facebook_preview.png'  # inside /assets/images/

  # Main landing page
  main:
    #logo:
      #img: 'acmsigspatial-full.png'
    links:
      - name: Call for paper
        relative_url: /cfp/
      # - name: Proceedings
      #   absolute_url: https://dl.acm.org/doi/proceedings/10.1145/3615891
      # - name: Program
      #   relative_url: /program/
      - name: SIGSPATIAL 2024
        absolute_url: https://sigspatial2024.sigspatial.org/
      #   disabled: true
      #   absolute_url: ''

  # Information boxes
  info_bars:
    # - title: GeoSim 2023 Proceedings is released!
    #   color: primary
    #   main_only: true
    #   text: |
    #     Please check out proceedings in ACM Digital Library.
    # - title: GeoSim 2023 Program is updated!
    #   color: primary
    #   main_only: true
    #   text: |
    #     Please check out Program.
    # - title: GeoSim 2024 is now open!
    #   color: primary
    #   main_only: true
    #   text: |
    #     Please check out Call for Paper.
    - title: Submission deadline is extend.
      color: primary
      main_only: true
      text: |
        Please check out Call for Paper.

    # - text: Upcoming info.
    #   color: warning
    #   pages_only: true

  # Live indications
  # live:
  #   date: 01.01.2020
  #   timezone: GMT+1
  #   stop:       240  # in minutes
  #   streaming:
  #     enable: true
  #     pause:     60  # in minutes
  #     prepend:    5  # in minutes
  #     extend:     5  # in minutes
  #   demo:
  #     enable: false
  #     duration: 300  # in seconds
  #     pause:     10  # in seconds

  map:
    # Initial map center point
    home_coord: 53.5615586,9.9848718
    # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
    # The following do match the Bootstrap design not too badly:
    #   - Hydda.Full
    #   - Thunderforest.Neighbourhood
    #   - Esri.WorldTopoMap
    map_provider: "OpenStreetMap.Mapnik"
    default_zoom: 17

  talks:
    # Talk categories
    main_categories:
      - name: Keynote
        color: info
      - name: Presentation
        color: success
      - name: Break
        color: dark

    # Hide icons on talk overview page
    hide_icons: false

  speakers:
    # Show first and last name
    show_firstname: true

  location:
    # Disable links to locations
    hide: false
    # URL of location / room overview page
    url: '/location'
    # Main page title shown on location/room navigation bar
    navbar_title: 'Location'
    # Show map on location main page
    map: true

  program:
    # URL of program page
    url: '/program'

    # Time steps in program table
    time_steps: 5 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: true


